WIFI_TOKENS = {
    b"MY_SSID_1": b"MY_PASSWORD_1",
    b"MY_SSID_2": b"MY_PASSWORD_2",
}
MQTT_SERVER = "MY_BROKER_URL_OR_IP"
MQTT_USER = "MY_BROKET_USER"
MQTT_PWD = "MY_BROKER_PASSWORD"
MQTT_TOPIC = b"MY_UBICATION/ms5607"
